gems:
  - bourbon
  - neat
  - octopress-autoprefixer

# Structure configuration
source: source
destination: build

assets:
  cachebust: soft

# Site settings
title: Homepage | Robert Borbély
description: Prototyping starter kit for Jekyll

# Name of project on Github
baseurl: 

# Build settings
markdown: kramdown

port: 3000
host: localhost
